apiVersion: v1
kind: Service
metadata:
  name: node-web-app-service
  labels:
    app: node-web-app
spec:
  selector:
    app: node-web-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 4500       # Port exposed externally on the Service
      targetPort: 4500 # Port your application listens on inside the pods
      nodePort: 31110  # NodePort (adjust as needed)
