apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app-deployment
  labels:
    app: node-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-web-app
  template:
    metadata:
      labels:
        app: node-web-app
    spec:
      containers:
        - name: node-web-app
          image: sindhusambasivam/hello_world:11  # Updated with the correct image name and tag
          ports:
            - containerPort: 4500  # Correct port configuration
