name: Run Localhost Service in GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  run-localhost-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Start Localhost Service
        run: |
          # Start your service on localhost:8000 (for example, a Node.js app)
          npm start &

          # Install socat
          sudo apt-get update && sudo apt-get install -y socat

          # Use socat to forward traffic from port 8001 to localhost:8000
          socat TCP-LISTEN:8001,fork TCP:localhost:8000
