name: SKCeles

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      KUBECONFIG_PASS: ${{ secrets.KUBECONFIG_PWD }}
      DOCKERHUB_REGISTRY:  sivashreek/kubn

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: SonarQube Analysis
        run: |
          curl -o sonar-scanner.zip -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-windows.zip
          echo "C:\\Users\\vipv\\sonar-scanner-5.0.1.3006-windows\\bin\\sonar-scanner.bat"

      - name: Run JMeter Tests
        uses: QAInsights/PerfAction@v3.1
        with:
          test-plan-path: ./CSVSample.jmx

      - name: Build and Push Docker image
        run: |
          docker build -t $DOCKERHUB_REGISTRY:${{ github.run_number }} .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push $DOCKERHUB_REGISTRY:latest
          
      - name: Run Docker image
        run: |
          docker run -p 8000:8000 $DOCKERHUB_REGISTRY:latest

      - name: Logout from Docker
        run: docker logout

      - name: Run Selenium Test
        run: |
          node helloworld.js &
          # Wait for server to start
          sleep 60
          # Install Selenium dependencies
          npm install selenium-webdriver chromedriver
          # Run Selenium test
          node selenium-test.js
          # Kill the Express.js server process
          pkill -f "node helloworld.js"
