name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build:
    runs-on: ubuntu-latest # Use the appropriate runner
    env:
      KUBECONFIG: config

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use the appropriate Node.js version

      - name: Install Dependencies
        run: |
          npm install

      - name: Test
        run: |
         npm test

      - name: Build Docker image
        run: |
         docker build -t sivashreek/kubn:${{ github.run_number }} .
       

      - name: Push Docker image
        run: |
         docker login -u sivashreek -p shreemani
         docker push sivashreek/kubn:${{ github.run_number }}

      - name: Set up Kubernetes
        run: |
           mkdir -p ~/.kube  # Create the .kube directory if it doesn't exist
           echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
             kubectl apply -f node-web-app-deployment.yaml 
             kubectl apply -f node-web-app-service.yaml
             shell: cmd


      - name: Clean up
        run: |
          docker logout
