name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      DOCKERHUB_REGISTRY: sindhusambasivam/hello_world
      DOCKERHUB_CREDENTIALS_ID: dockerhub

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # ... other steps ...

      - name: Normalize DOCKERHUB_REGISTRY
        run: |
          # Convert DOCKERHUB_REGISTRY to lowercase
          DOCKERHUB_REGISTRY_LOWER=$(echo $DOCKERHUB_REGISTRY | tr '[:upper:]' '[:lower:]')
          echo "Normalized DOCKERHUB_REGISTRY: $DOCKERHUB_REGISTRY_LOWER"
          echo "::set-env name=DOCKERHUB_REGISTRY::$DOCKERHUB_REGISTRY_LOWER"
        shell: bash

      - name: Build Docker Image
        run: |
          docker build -t $DOCKERHUB_REGISTRY:${GITHUB_RUN_NUMBER} .
        shell: cmd

      # ... other steps ...

