on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'SS2199/CICD'
        required: true

jobs:
  use_api:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          # Install the GitHub CLI (gh)
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Set up Git
        run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"

      - name: Use API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          repository_name="${{ github.event.inputs.repository }}"
          gh api repos/${repository_name}/issues
